version: '3.1'

services:
  db:
    image: mariadb:latest
    ports:
      - 3306:3306 
    environment:
      MYSQL_ROOT_PASSWORD: root

  phpmyadmin:
    image: phpmyadmin
    ports:
      - 5050:80
    environment:
      - PMA_PORT=3306